[package]
name = "filte-rs"
version = "0.1.0"
edition = "2021"
default-run = "filter"

[[bin]]
name = "filter"
path = "src/filter.rs"

[dependencies]
eyre = "0.6.12"
glob = "0.3.1"
regex = "1.10.5"
thiserror = "1.0.61"
